config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Extending Devise - Custom Routing
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    path: '', # optional namespace or empty string for no space
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup',
      invitation: 'invite'
    }
  root 'home#index'

  resources :reports, only: [:create] do
    get :autocomplete_category, :on => :collection
    get :autocomplete_config, :on => :collection
    # Search box
    collection do
      get :search
      post :import
    end
  end

  resources :posts, path: "/module", only: [:index, :show, :destroy] do
    resources :reports, only: [:show] do
      get :autocomplete_category_name, :on => :collection
      get :autocomplete_report_config, :on => :collection
      # Search box
      collection do
        get :search
      end
    end
    resources :categories, only: [:show]
    resources :source_files, path: "/file", only: [:index, :show, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end
  end

  # For Build Dropdown Menu
  get "/update_builds_menu" => "products#update_builds_menu"

  get "/search_report" => "reports#search"

  # Check if user's password correct before delete account
  post "/delete_account" => "accounts#checkpass"

  get '*anything' => 'errors#routing_error'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    page = (params[:page] || 1).to_i
  	@post = Post.find_by_slug(params[:post_id])
    @report = @post.reports.find(params[:id])
    @category = @report.category
    @reports_for_cart = @post.mi_reports.where('category_id = ? AND published_at = ?', 
    	@report.category_id, @report.published_at).order("published_at DESC")
  	@reports = @reports_for_cart.page(page)
  end

  def search
    @posts = Post.all
    @post = Post.find_by_slug(params[:post_id]) if params[:post_id]
    @category = @post.categories.find_by_id(params[:category]["id"]) if params[:category]
    page = (params[:page] || 1).to_i

    # For rendering contents by click tab after search
    if params[:from_category]
      @category = @post.categories.find(params[:from_category])
      reports_by_all_config = @category.reports.where(config: 'ALL')
    elsif params[:from_report] && params[:show_config] == 'all'
      @report = @post.reports.find(params[:from_report])
      @category = @report.category
      @reports_for_cart = @post.reports.where('config != ? AND category_name = ? AND published_at = ?', 
        'ALL', @report.category_name, @report.published_at).order("published_at DESC")
      @reports = @reports_for_cart.page(page)
    else
      if params[:post_id]
        reports_by_all_config = @post.reports.where(config: 'ALL')
      end
    end

    if params[:date].present? && params[:date] == 'today'
      if @post.reports.count == 0
        redirect_to post_path(@post), alert: "抱歉，沒有資料！"
        return
      else
        redirect_to post_path(@post)
      end
    elsif params[:date].present? && params[:date] == 'yesterday'
      if @post.reports.count == 0
        redirect_to post_path(@post), alert: "抱歉，沒有資料！"
        return
      else
        redirect_to post_path(@post)
      end
    elsif params[:commit] == 'Search' || params[:commit] == 'GlobalSearch'
      # For search function
      category = params[:category]
      date_from = params[:date_range][0, 10] if params[:date_range]
      date_to = params[:date_range][13, 10] if params[:date_range]
      fix_datetime = params[:no_date_range] if params[:no_date_range]

      date = params[:date] if params[:date]
      date1 = params[:date1] if params[:date1]
      date2 = params[:date2] if params[:date2]
      date3 = params[:date3] if params[:date3]
      search_type = params[:search_type] if params[:search_type]

      t = Report.arel_table
      @reports_for_cart = Report.where(post_id: @post)
      @reports_for_cart = @reports_for_cart.where(t[:category_name].matches("#{category}")) if category.present?

      # Multiple Date Search
      if date1.present? || date2.present? || date3.present? && !search_type.present?
        dates_for_filter = []
        [date1, date2, date3].each do |date|
          dates_for_filter << date if date.present?
        end
        @reports_for_cart = @reports_for_cart.where(published_at: [dates_for_filter])
        @dates_selected = @reports_for_cart.select("distinct(published_at)")
        @dates_selected_count = @dates_selected.count

        report_for_tmp = @reports_for_cart
        @reports_for_cart = report_for_tmp.order("published_at ASC")
        @distinct_date = @reports_for_cart.select("distinct(published_at)")
        
        @reports = report_for_tmp.order("category_id ASC, published_at ASC").page(page)
        @reports_summarize = @reports_for_cart.group_by(&:category_name)
      # Date Range Search
      elsif date_from.present? && date_to.present? && search_type.present? && search_type == "Range"
        if date_from != date_to # Search for multiple days (ex. Jun 20 ~ Jun 23)
          dates_for_filter = []
          search_date_range = ("#{date_from}".."#{date_to}")
          search_date_range.each do |the_date|
            dates_for_filter.append(the_date)
          end
          @reports_for_cart = @reports_for_cart.where(published_at: [dates_for_filter])
          report_for_tmp = @reports_for_cart
          @reports_for_cart = report_for_tmp.order("published_at ASC")
          @distinct_date = @reports_for_cart.select("distinct(published_at)")
          
          @reports = report_for_tmp.order("category_id ASC, published_at ASC").page(page)
          @reports_summarize = report_for_tmp.select('category_name, MAX(shares_percentage) as best_sp, MIN(shares_percentage) as worst_sp, MAX(closing_percentage) as best_cp, MIN(closing_percentage) as worst_cp').group(:category_id, :category_name)

          # Get all dates that best shares percentage occurs
          @best_sp_dates = []
          @reports_summarize.each do |item|
            matched_dates = @reports_for_cart.where(category_name: item.category_name).where("shares_percentage > ? AND shares_percentage < ?", item.best_sp - 0.00001, item.best_sp + 0.00001)
            @best_sp_dates.append(matched_dates)
          end

          # Get all dates that worst shares percentage occurs
          @worst_sp_dates = []
          @reports_summarize.each do |item|
            matched_dates = @reports_for_cart.where(category_name: item.category_name).where("shares_percentage > ? AND shares_percentage < ?", item.worst_sp - 0.00001, item.worst_sp + 0.00001)
            @worst_sp_dates.append(matched_dates)
          end

          # Get all dates that best closing percentage occurs
          @best_cp_dates = []
          @reports_summarize.each do |item|
            matched_dates = @reports_for_cart.where(category_name: item.category_name).where("closing_percentage > ? AND closing_percentage < ?", item.best_cp - 0.00001, item.best_cp + 0.00001)
            @best_cp_dates.append(matched_dates)
          end

          # Get all dates that worst closing percentage occurs
          @worst_cp_dates = []
          @reports_summarize.each do |item|
            matched_dates = @reports_for_cart.where(category_name: item.category_name).where("closing_percentage > ? AND closing_percentage < ?", item.worst_cp - 0.00001, item.worst_cp + 0.00001)
            @worst_cp_dates.append(matched_dates)
          end
        else
          if params[:category] == ""
            latest_date = @reports_for_cart.maximum('published_at')
            @reports_for_cart = @reports_for_cart.where(published_at: latest_date)
          end
        end
      elsif date.present? && search_type.present? && search_type == "Stock"
      	@reports_for_cart = MiReport.where(post_id: @post)
        @reports_for_cart = @reports_for_cart.where(category_id: @category.id, published_at: date)
        @reports = @reports_for_cart.order("stock_code ASC").page(page)
        @distinct_date = @reports_for_cart.select("distinct(published_at)")
      end
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def best_percentage_chart_data(reports)
    start_time = reports.last.published_at
    end_time = reports.first.published_at
    post_id = reports.first.post_id
    if controller.controller_name == "reports"
      # For search build page
      datetime = reports.select("distinct(published_at)")
    else
      # For general build page
      datetime = Report.where("post_id = ? AND published_at BETWEEN ? AND ?", post_id, start_time, end_time).select("distinct(published_at)")
    end
    datetime.map do |date|
    {
      published_at: date.published_at.to_datetime.to_formatted_s(:long),
      best1_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).first.try(:best_shares_percentage),
      best1_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).first.try(:best_closing_percentage),
      best1_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).first.try(:category_name),
      best1_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).first.try(:category_name),
      
      best2_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(1).first.try(:best_shares_percentage),
      best2_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(1).first.try(:best_closing_percentage),
      best2_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(1).first.try(:category_name),
      best2_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(1).first.try(:category_name),
      
      best3_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(2).first.try(:best_shares_percentage),
      best3_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(2).first.try(:best_closing_percentage),
      best3_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(2).first.try(:category_name),
      best3_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(2).first.try(:category_name),
      
      best4_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(3).first.try(:best_shares_percentage),
      best4_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(3).first.try(:best_closing_percentage),
      best4_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(3).first.try(:category_name),
      best4_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(3).first.try(:category_name),
      
      best5_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(4).first.try(:best_shares_percentage),
      best5_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(4).first.try(:best_closing_percentage),
      best5_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(4).first.try(:category_name),
      best5_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(4).first.try(:category_name),
    }
    end
  end

  def config_accu_yield_bar_chart_data(reports)
    category = reports.first.category_name
    config = reports.first.config
    datetime_start = reports.minimum('published_at')
    datetime_end = reports.maximum('published_at')

    if params[:data_period].present? && params[:data_period] == "hourly"
      # If parameter present, show each hour's report
      overflow_accu_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate > ?", config, category, datetime_start, datetime_end, 100.00).count
      great_accu_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, category, datetime_start, datetime_end, 99.51, 100.00).count
      bad_accu_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, category, datetime_start, datetime_end, 90.00, 99.50).count
      worse_accu_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, category, datetime_start, datetime_end, 0.00, 89.99).count
      no_input_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate IS NULL", config, category, datetime_start, datetime_end).count
    else
      # By default, only show latest hour's report for each day
      overflow_accu_yield = reports.where("yield_rate > ?", 100.00).count
      great_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 99.51, 100.00).count
      bad_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 90.00, 99.50).count
      worse_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 0.00, 89.99).count
      no_input_yield = reports.where("yield_rate IS NULL").count
    end

    overflow_accu_yield_rate = ((overflow_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    great_accu_yield_rate = ((great_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    bad_accu_yield_rate = ((bad_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    worse_accu_yield_rate = ((worse_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    no_input_yield_rate = ((no_input_yield.to_f / reports.count.to_f) * 100).round(2)

    range_array = [overflow_accu_yield, great_accu_yield, bad_accu_yield, worse_accu_yield, no_input_yield]
    title = ['Overflow Accu Yield', 'Verified Accu Yield', 'Bad Accu Yield', 'Worse Accu Yield', 'No Input']
    percent = [overflow_accu_yield_rate, great_accu_yield_rate, bad_accu_yield_rate, worse_accu_yield_rate, no_input_yield_rate]

    range_array.map.with_index do |range, index| {  
      value: range,
      label: title[index],
      percent: percent[index]
    }
    end
  end

  def config_daily_yield_bar_chart_data(reports)
    category = reports.first.category_name
    config = reports.first.config
    datetime_start = reports.minimum('published_at')
    datetime_end = reports.maximum('published_at')

    if params[:data_period].present? && params[:data_period] == "hourly"
      # If parameter present, show each hour's report
      overflow_daily_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today > ?", config, category, datetime_start, datetime_end, 100.00).count
      great_daily_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, category, datetime_start, datetime_end, 99.51, 100.00).count
      bad_daily_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, category, datetime_start, datetime_end, 90.00, 99.50).count
      worse_daily_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, category, datetime_start, datetime_end, 0.00, 89.99).count
      no_input_yield = Report.where("config = ? AND category_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today IS NULL", config, category, datetime_start, datetime_end).count
    else
      # By default, only show latest hour's report for each day
      overflow_daily_yield = reports.where("yield_rate_today > ?", 100.00).count
      great_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 99.51, 100.00).count
      bad_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 90.00, 99.50).count
      worse_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 0.00, 89.99).count
      no_input_yield = reports.where("yield_rate_today IS NULL").count
    end

    overflow_daily_yield_rate = ((overflow_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    great_daily_yield_rate = ((great_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    bad_daily_yield_rate = ((bad_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    worse_daily_yield_rate = ((worse_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    no_input_yield_rate = ((no_input_yield.to_f / reports.count.to_f) * 100).round(2)

    range_array = [overflow_daily_yield, great_daily_yield, bad_daily_yield, worse_daily_yield, no_input_yield]
    title = ['Overflow Daily Yield', 'Verified Daily Yield', 'Bad Daily Yield', 'Worse Daily Yield', 'No Input']
    percent = [overflow_daily_yield_rate, great_daily_yield_rate, bad_daily_yield_rate, worse_daily_yield_rate, no_input_yield_rate]

    range_array.map.with_index do |range, index| {  
      value: range,
      label: title[index],
      percent: percent[index]
    }
    end
  end
end

app/views/reports/_best_percentage_cart.html.haml
%div
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "best-shares-p", "data-toggle" => "tab", :href => "#best-shares-p", :role => "tab"} 成交股數比
    %li{:role => "presentation"}
      %a{"aria-controls" => "best-closing-p", "data-toggle" => "tab", :href => "#best-closing-p", :role => "tab"} 成交金額比

  .tab-content
    #best-shares-p.tab-pane.fade.in.active{:role => "tabpanel"}
      - if @reports_for_cart.count > 0
        .small{style: "margin-top: 15px; text-align: center;"}
          %strong
            成交股數比前五位
        .chart-tags
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #cb4b4b;"}
            %span.badge-category 少量佔比 (0 ~ 9.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #f8aa33;"}
            %span.badge-category 一般佔比 (10.00 ~ 49.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #1fbba6;"}
            %span.badge-category 多量佔比 (50.00 ~ 100 %)

        = content_tag :div, "", id: "best-shares-p-yield-data", data: {reports: config_best_percentage_chart_data(@reports_for_cart, @category)}
      - else
        .well{:style => "margin-top: 10px;"}
          .blankslate.text-center
            %h3 沒有資料
            %p 抱歉，沒有資料可以呈現圖表

    #best-closing-p.tab-pane.fade{:role => "tabpanel"}
      - if @reports_for_cart.count > 0
        .small{style: "margin-top: 15px; text-align: center;"}
          %strong
            成交金額比前五位
        .chart-tags
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #ff7070;"}
            %span.badge-category 少量佔比 (0 ~ 9.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #ffc652;"}
            %span.badge-category 一般佔比 (10.00 ~ 49.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #4da74d;"}
            %span.badge-category 多量佔比 (50.00 ~ 100 %)

        = content_tag :div, "", id: "best-closing-p-yield-data", data: {reports: config_best_percentage_chart_data(@reports_for_cart, @category)}
      - else
        .well{:style => "margin-top: 10px;"}
          .blankslate.text-center
            %h3 沒有資料
            %p 抱歉，沒有資料可以呈現圖表
            
:javascript
  jQuery(function() {
    $('ul.nav a').on('shown.bs.tab', function (e) {
      best_shares_percentage_graph.redraw();
      best_closing_percentage_graph.redraw();
      $('svg').css({ width: '100%' });
    });

    var best_shares_percentage_graph = Morris.Bar({
      element: 'best-shares-p-yield-data',
      smooth: true,
      continuousLine: true,
      behaveLikeLine: true,
      barColors: function(row, series, type) {
        if (type === 'bar') {
          if (row.y >= 50.00 && row.y <= 100) {
            return '#1fbba6';
          } else if (row.y >= 10.00 && row.y <= 49.99) {
            return '#f8aa33';
          } else if (row.y >= 0 && row.y <= 9.99) {
            return '#cb4b4b';
          }
        } else {
          return '#000';
        }
      },
      lineWidth: 4,
      fillOpacity: 0.8,
      resize: true,
      hideHover: 'auto',
      continuousLine: true,
      data: $('#best-shares-p-yield-data').data('reports'),
      goals: [0, 50, 100],
      goalLineColors: ['#e74c3c', '#e67e22', '#2ecc71'],
      xkey: 'published_at',
      ykeys: ['best1_shares_percentage', 'best2_shares_percentage', 'best3_shares_percentage', 'best4_shares_percentage', 'best5_shares_percentage'],
      labels: ['best1_shares_percentage_index', 'best2_shares_percentage_index', 'best3_shares_percentage_index', 'best4_shares_percentage_index', 'best5_shares_percentage_index'],
      "hoverCallback":  function(index, options, content){
        var row = options.data[index]
        datetime = '<p><b>' + row.published_at + '</b></p>'
        var top1_index = row.best1_shares_percentage + options.postUnits;
        var top2_index = row.best2_shares_percentage + options.postUnits;
        var top3_index = row.best3_shares_percentage + options.postUnits;
        var top4_index = row.best4_shares_percentage + options.postUnits;
        var top5_index = row.best5_shares_percentage + options.postUnits;

        p_index1 = '<div style="color: #555;"><strong>Top1: </strong>' + row.best1_shares_percentage_index + ' (' + top1_index + ')</div>'
        p_index2 = '<div style="color: #555;"><strong>Top2: </strong>' + row.best2_shares_percentage_index + ' ('  + top2_index + ')</div>'
        p_index3 = '<div style="color: #555;"><strong>Top3: </strong>' + row.best3_shares_percentage_index + ' ('  + top3_index + ')</div>'
        p_index4 = '<div style="color: #555;"><strong>Top4: </strong>' + row.best4_shares_percentage_index + ' ('  + top4_index + ')</div>'
        p_index5 = '<div style="color: #555;"><strong>Top5: </strong>' + row.best5_shares_percentage_index + ' ('  + top5_index + ')</div>'
        
        return [datetime, p_index1, p_index2, p_index3, p_index4, p_index5]
      },
      trendLine: true,
      postUnits: '%',
      ymin: 'auto',
      ymax: 'auto',
      parseTime: false,
      barOpacity: 0.8,
      behaveLikeLine: true
    });

    var best_closing_percentage_graph =  Morris.Bar({
      element: 'best-closing-p-yield-data',
      smooth: true,
      continuousLine: true,
      behaveLikeLine: true,
      barColors: function(row, series, type) {
        if (type === 'bar') {
          if (row.y >= 50.00 && row.y <= 100) {
            return '#4da74d';
          } else if (row.y >= 10.00 && row.y <= 49.99) {
            return '#ffc652';
          } else if (row.y >= 0 && row.y <= 9.99) {
            return '#ff7070';
          }
        } else {
          return '#000';
        }
      },
      lineWidth: 4,
      fillOpacity: 0.8,
      resize: true,
      hideHover: 'auto',
      continuousLine: true,
      data: $('#best-closing-p-yield-data').data('reports'),
      goals: [0, 50, 100],
      goalLineColors: ['#e74c3c', '#e67e22', '#2ecc71'],
      xkey: 'published_at',
      ykeys: ['best1_closing_percentage', 'best2_closing_percentage', 'best3_closing_percentage', 'best4_closing_percentage', 'best5_closing_percentage'],
      labels: ['best1_closing_percentage_index', 'best2_closing_percentage_index', 'best3_closing_percentage_index', 'best4_closing_percentage_index', 'best5_closing_percentage_index'],
      "hoverCallback":  function(index, options, content){
        var row = options.data[index]
        datetime = '<p><b>' + row.published_at + '</b></p>'
        var top1_index = row.best1_closing_percentage + options.postUnits;
        var top2_index = row.best2_closing_percentage + options.postUnits;
        var top3_index = row.best3_closing_percentage + options.postUnits;
        var top4_index = row.best4_closing_percentage + options.postUnits;
        var top5_index = row.best5_closing_percentage + options.postUnits;

        c_index1 = '<div style="color: #555;"><strong>Top1: </strong>' + row.best1_closing_percentage_index + ' (' + top1_index + ')</div>'
        c_index2 = '<div style="color: #555;"><strong>Top2: </strong>' + row.best2_closing_percentage_index + ' ('  + top2_index + ')</div>'
        c_index3 = '<div style="color: #555;"><strong>Top3: </strong>' + row.best3_closing_percentage_index + ' ('  + top3_index + ')</div>'
        c_index4 = '<div style="color: #555;"><strong>Top4: </strong>' + row.best4_closing_percentage_index + ' ('  + top4_index + ')</div>'
        c_index5 = '<div style="color: #555;"><strong>Top5: </strong>' + row.best5_closing_percentage_index + ' ('  + top5_index + ')</div>'
        
        return [datetime, c_index1, c_index2, c_index3, c_index4, c_index5]
      },
      postUnits: '%',
      ymin: 'auto',
      ymax: 'auto',
      parseTime: false,
      barOpacity: 0.8,
      behaveLikeLine: true
    });
  });

app/views/reports/_chart_by_search.html.haml
- if params[:category].present? && params[:category] != ""
  = render :partial => "reports/best_percentage_cart"
- elsif params[:from_category].present? && params[:from_category] != ""
  = render :partial => "categories/station_yield_cart"
- elsif params[:from_report].present? && params[:from_report] != ""
  = render :partial => "configs/yield_ratio_chart"
- else
  = render :partial => "posts/worst_yield_cart"

app/views/reports/search.html.haml
- navigation_add 'Search Results', search_reports_path

%h2.page-header
  資料查詢結果
  %small
    %strong
      - if params[:product_id].present?
        = link_to @product.title, posts_path
      - if params[:post_id].present?
        &gt;
        = link_to @post.title, post_path(@post)
      - if params[:category].present?
        &gt;
        = link_to params[:category], post_category_path(@post, @category)
      - if params[:config].present?
        &gt;
        #{params[:config]}
.form-group
  .row
    .col-md-12
      #yield-report
        = render :partial => "shared/yield_report"

app/views/reports/show.html.haml
- navigation_add "功能模組", posts_path
- navigation_add @post.title, post_path(@post)
- navigation_add @category.name, post_report_path(@post)

%h2.page-header
  = @category.name
  %small #{@report.published_at.to_date.to_formatted_s(:long)} 的交易資料
  
.row
  .container
    .form-group
    - if @reports.count > 0
      #yield-report
        = render :partial => "yield_by_config"

app/views/reports/show.js.erb
//$('#yield-items').html("<%= j(render :partial => 'shared/yield_items') %>");
$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
$('#paginator-top').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
$('#page-info').html("<%= j(render :partial => 'shared/page_info_scroll') %>");
$("#paginator .pagination").rPage();

// Append new report data
$("<%=j render(:partial => 'shared/items', :object => @reports) %>").appendTo($(".infinite-table"));
// Update pagination link
<% if @reports.last_page? %>
  $('.pagination').html("沒有更多資料了！");
<% else %>
  //$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
  $('#paginator').html('<%= escape_javascript(link_to_next_page(@reports, '載入更多資料', params: params, :remote => true).to_s) %>');
<% end %>